export const JobStatus = {
  QUEUED: 'QUEUED',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  INTERRUPTED: 'INTERRUPTED'
};

export const ErrorCategory = {
  PROVIDER_AUTH: 'PROVIDER_AUTH',
  PROVIDER_EXEC: 'PROVIDER_EXEC',
  PROVIDER_CAPABILITY: 'PROVIDER_CAPABILITY',
  NETWORK: 'NETWORK',
  TIMEOUT: 'TIMEOUT',
  CANCELLED: 'CANCELLED',
  DATABASE: 'DATABASE',
  SCHEDULER: 'SCHEDULER',
  SSH: 'SSH',
  DOCKER: 'DOCKER',
  ATTACHMENT: 'ATTACHMENT',
  AGENT_HUB_RESTART: 'AGENT_HUB_RESTART',
  INTERNAL: 'INTERNAL'
};
